/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App_Interfaces;

/**
 *
 * @author Juan Pablo
 */
public class Caso_InicioDecision extends javax.swing.JFrame {

    /**
     * Creates new form Caso_InicioDecision
     */
    public Caso_InicioDecision() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_IngresaUsuario1 = new javax.swing.JLabel();
        jButton_Si = new javax.swing.JButton();
        jButton_No = new javax.swing.JButton();
        jLabel_IngresaUsuario2 = new javax.swing.JLabel();
        jButton_Si1 = new javax.swing.JButton();
        jButton_No1 = new javax.swing.JButton();

        jLabel_IngresaUsuario1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel_IngresaUsuario1.setText("¿Iniciar configuración?");

        jButton_Si.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_Si.setText("Si");
        jButton_Si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SiActionPerformed(evt);
            }
        });

        jButton_No.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_No.setText("No");
        jButton_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NoActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel_IngresaUsuario2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel_IngresaUsuario2.setText("¿Iniciar configuración?");

        jButton_Si1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_Si1.setText("Si");
        jButton_Si1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Si1ActionPerformed(evt);
            }
        });

        jButton_No1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton_No1.setText("No");
        jButton_No1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_No1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton_Si1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_No1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_IngresaUsuario2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_IngresaUsuario2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Si1)
                    .addComponent(jButton_No1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_SiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SiActionPerformed
        // boton si

        dispose();

        new Caso_Menu().setVisible(true);
    }//GEN-LAST:event_jButton_SiActionPerformed

    private void jButton_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NoActionPerformed
        // boton no

        dispose();
        new Caso_Actividades().setVisible(true);

    }//GEN-LAST:event_jButton_NoActionPerformed

    private void jButton_Si1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Si1ActionPerformed
        // boton si

        dispose();

        new Caso_Menu().setVisible(true);
    }//GEN-LAST:event_jButton_Si1ActionPerformed

    private void jButton_No1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_No1ActionPerformed
        // boton no

        dispose();
        new Caso_Actividades().setVisible(true);

    }//GEN-LAST:event_jButton_No1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caso_InicioDecision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caso_InicioDecision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caso_InicioDecision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caso_InicioDecision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caso_InicioDecision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_No;
    private javax.swing.JButton jButton_No1;
    private javax.swing.JButton jButton_Si;
    private javax.swing.JButton jButton_Si1;
    private javax.swing.JLabel jLabel_IngresaUsuario1;
    private javax.swing.JLabel jLabel_IngresaUsuario2;
    // End of variables declaration//GEN-END:variables
}
